MuonsMatching_Eta_Pt2to5:
  sample: DYLL_M50
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Muons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 13"
        - "{pt} > 2"
        - "{pt} < 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1gmtMuon:default: "eta"
    L1gmtMuon:dR0p6: "eta"
    L1gmtTkMuon:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (2-5 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

MuonsMatching_Eta_Pt15toInf:
  sample: DYLL_M50
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "eta"
    label: "Gen Muons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 13"
        - "{pt} > 15"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1gmtMuon:default: "eta"
    L1gmtTkMuon:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>15 GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
