PhotonsTrigger_Barrel:
  sample: Hgg
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 22"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1EG:default:barrel: "pt"
    L1tkPhoton:NoIso:barrel: "pt"
    L1tkPhoton:Iso:barrel: "pt"
  thresholds: [8]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
  binning:
    min: 0
    max: 100
    step: 1.5

PhotonsTrigger_Endcap:
  sample: Hgg
  version: V38nano
  match_test_to_ref: True
  reference_object:
    object: "GenPart"
    x_arg: "pt"
    label: "Gen Photons"
    cuts:
      event:
        - "(({statusFlags}>>7)&1) == 1"
        - "abs({pdgId}) == 22"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1EG:default:endcap: "pt"
    L1tkPhoton:NoIso:endcap: "pt"
    L1tkPhoton:Iso:endcap: "pt"
  thresholds: [8]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
  binning:
    min: 0
    max: 100
    step: 1.5
