V33nano:
  Hgg:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v33/GluGluHToGG_M-125_TuneCP5_14TeV-powheg-pythia8/GluGluHToGG_131_200PU_IB1400pre3V1/240221_221354/0000/test_*.root
    trees_branches:
      Events:
        GenPart: [pt, eta, phi, pdgId, statusFlags]
        L1tkPhoton: "all" 
        # L1tkElectron: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
  DYLL_M50:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v33_fromEmyr/dyToLL.root
    trees_branches:
      Events:
        GenPart: "all" 
        L1gmtTkMuon: "all" 
        L1gmtMuon: "all"
        L1tkElectron: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
  TT:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v33_fromEmyr/ttbar.root
    trees_branches:
      Events:
        # gen
        GenJet: [pt, eta, phi, partonFlavour]
        GenJetAK8: [pt, eta, phi]
        GenMET: "all"
        # sums
        L1puppiMET: [pt, phi]
        L1puppiMLMET: [pt]
        L1puppiJetSC4sums: [pt, phi]
        L1puppiHistoJetSums: [pt, phi]
        # jets
        L1puppiJetSC4: [pt, eta, phi]
        L1puppiJetSC8: [pt, eta, phi]
        L1puppiExtJetSC4: [pt, eta, phi, btagScore]
        L1puppiJetHisto: [pt, eta, phi]
        L1caloJet: [pt, eta, phi]
        L1TrackMET: [pt]
        L1TrackHT: [ht, mht]
        L1TrackJet: [pt, eta, phi]
  VBFHToTauTau:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v33_fromEmyr/vbfHTauTau.root
    trees_branches:
      Events:
        GenVisTau: "all" 
        L1nnPuppiTau: "all" 
        L1hpsTau: "all" 
        L1caloTau: "all" 
        L1nnCaloTau: "all"
  MinBias:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v33_fromEmyr/minbias.root
    trees_branches:
      Events:
        ## PV
        L1PV: [z0]
        ## EG
        L1tkPhoton: "all" 
        L1tkElectron: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
        ## MUONS
        L1gmtTkMuon: "all" 
        L1gmtMuon: "all"  # aka gmtMuon
        ## TAUS
        L1nnPuppiTau: "all" 
        L1hpsTau: "all" 
        L1caloTau: "all" 
        L1nnCaloTau: "all"
        ## MET/Sums
        L1puppiMET: [pt, phi]
        L1puppiMLMET: [pt]
        L1puppiJetSC4sums: [pt, phi]
        L1puppiHistoJetSums: [pt, phi]
        # jets
        L1puppiJetSC4: [pt, eta, phi]
        L1puppiJetSC8: [pt, eta, phi]
        L1puppiExtJetSC4: [pt, eta, phi, btagScore]
        L1puppiJetHisto: [pt, eta, phi]
        L1caloJet: [pt, eta, phi]
        ## track-only
        L1TrackMET: [pt]
        L1TrackHT: [ht, mht]
        L1TrackJet: [pt, eta, phi]