JetDefaultRates:
  sample: MinBias
  version: V31
  test_objects:
    - phase1PuppiJet:default
    - seededConePuppiJet:default
    # - seededConeExtendedPuppiJet:default
    - trackerJet:default
    - caloJet:default
  binning:
    min: 40
    max: 420
    step: 20

JetsByRegion:
  sample: MinBias
  version: V31
  test_objects:
    - phase1PuppiJet:default:barrel
    - phase1PuppiJet:default:endcap
    - phase1PuppiJet:default:forward
    - seededConePuppiJet:default:barrel
    - seededConePuppiJet:default:endcap
    - seededConePuppiJet:default:forward
    - caloJet:default:barrel
    - caloJet:default:endcap
    - caloJet:default:forward
  binning:
    min: 40
    max: 420
    step: 20

JetExtendedRates:
  sample: MinBias
  version: V31
  test_objects:
    - seededConePuppiJet:default:barrel
    - seededConePuppiJet:default:endcap
    - seededConePuppiJet:default:forward
    - seededConeExtendedPuppiJet:default:barrel
    - seededConeExtendedPuppiJet:default:endcap
    - seededConeExtendedPuppiJet:default:forward
