TausMatchingBarrel:
  sample: VBFHToTauTau
  version: V42nano
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "pt"
    label: "Gen Taus"
    cuts:
      event:
        # - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1nnPuppiTau:default: "pt"
    # L1hpsTau:default: "pt"
    L1caloTau:default: "pt"
    # L1nnCaloTau:default: "pt"
#     L1caloTau:PtGe20: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 150
    step: 6

TausMatchingEndcap:
  sample: VBFHToTauTau
  version: V42nano
  match_test_to_ref: True
  reference_object:
    object: "GenVisTau"
    x_arg: "pt"
    label: "Gen Taus"
    cuts:
      event:
        # - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1nnPuppiTau:default: "pt"
    # L1hpsTau:default: "pt"
    L1caloTau:default: "pt"
    # L1nnCaloTau:default: "pt"
#     L1caloTau:PtGe20: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 150
    step: 6
