V36nano_noTT:
  Hgg:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v36/GluGluHToGG_M-125_TuneCP5_14TeV-powheg-pythia8/GluGluHToGG_131_200PU_myIBv6_noTkTrg/240403_211847/0000/L1Nano_*.root
    trees_branches:
      Events:
        GenPart: [pt, eta, phi, pdgId, statusFlags]
        L1tkPhoton: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
  DYLL_M50:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v36/DYToLL_M-50_TuneCP5_14TeV-pythia8/DY_M50_131_200PU_myIBv6_noTkTrg_resub/240403_214206/0000/L1Nano_*.root
    trees_branches:
      Events:
        GenPart: "all" 
        ## EG
        L1tkElectron: "all" 
        L1EGbarrel: "all" 
        L1EGendcap: "all" 
        ## Muons
        L1gmtTkMuon: "all" 
        L1gmtMuon: "all"
        L1gmtDispMuon: "all"
        ## TF Muons
        L1MuonKMTF: "all"
        L1MuonOMTF: "all"
        L1MuonEMTF: "all"
        L1DispMuonKMTF: "all"
        L1DispMuonOMTF: "all"
        L1DispMuonEMTF: "all"
  TT:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v36/TT_TuneCP5_14TeV-powheg-pythia8/TT_131_200PU_myIBv6_noTkTrg/240403_211802/0000/L1Nano_*.root
    trees_branches:
      Events:
        # gen
        GenJet: [pt, eta, phi, partonFlavour]
        GenJetAK8: [pt, eta, phi]
        GenMET: "all"
        # sums
        L1puppiMET: [pt, phi]
        L1puppiMLMET: [pt]
        L1puppiJetSC4sums: [pt, phi]
        L1puppiHistoJetSums: [pt, phi]
        # jets
        L1puppiJetSC4: [pt, eta, phi]
        L1puppiJetSC8: [pt, eta, phi]
        L1puppiExtJetSC4: [pt, eta, phi, btagScore]
        L1puppiJetHisto: [pt, eta, phi]
        L1caloJet: [pt, eta, phi]
        L1TrackMET: [pt]
        L1TrackHT: [ht, mht]
        L1TrackJet: [pt, eta, phi]
  VBFHToTauTau:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v36/VBFHToTauTau_M-125_TuneCP5_14TeV-powheg-pythia8/VBFHToTauTau_131_200PU_myIBv6_noTkTrg_resub/240403_214225/0000/L1Nano_*.root
    trees_branches:
      Events:
        GenVisTau: "all" 
        L1nnPuppiTau: "all" 
        L1hpsTau: "all" 
        L1caloTau: "all" 
        L1nnCaloTau: "all"
  # MinBias:
  #   ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v33_fromEmyr/minbias.root
  #   trees_branches:
  #     Events:
  #       ## PV
  #       L1PV: [z0]
  #       ## EG
  #       L1tkPhoton: "all" 
  #       L1tkElectron: "all" 
  #       L1EGbarrel: "all" 
  #       L1EGendcap: "all" 
  #       ## MUONS
  #       L1gmtTkMuon: "all" 
  #       L1gmtMuon: "all"  # aka gmtMuon
  #       ## TAUS
  #       L1nnPuppiTau: "all" 
  #       L1hpsTau: "all" 
  #       L1caloTau: "all" 
  #       L1nnCaloTau: "all"
  #       ## MET/Sums
  #       L1puppiMET: [pt, phi]
  #       L1puppiMLMET: [pt]
  #       L1puppiJetSC4sums: [pt, phi]
  #       L1puppiHistoJetSums: [pt, phi]
  #       # jets
  #       L1puppiJetSC4: [pt, eta, phi]
  #       L1puppiJetSC8: [pt, eta, phi]
  #       L1puppiExtJetSC4: [pt, eta, phi, btagScore]
  #       L1puppiJetHisto: [pt, eta, phi]
  #       L1caloJet: [pt, eta, phi]
  #       ## track-only
  #       L1TrackMET: [pt]
  #       L1TrackHT: [ht, mht]
  #       L1TrackJet: [pt, eta, phi]
  HtoLLPto4mu_Ctau900mm:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v36/HTo2LongLivedTo4mu_MH-125_MFF-12_CTau-900mm_TuneCP5_14TeV-pythia8/HtoLLPto4mu_Ctau90cm_131_L1Fix_myIBv6_noTkTrg_resub/240403_222836/0000/L1Nano_*.root
    trees_branches:
      Events:
        GenPart: "all" 
        ## Muons
        L1gmtTkMuon: "all" 
        L1gmtMuon: "all"
        L1gmtDispMuon: "all"
        ## TF Muons
        L1MuonKMTF: "all"
        L1MuonOMTF: "all"
        L1MuonEMTF: "all"
        L1DispMuonKMTF: "all"
        L1DispMuonOMTF: "all"
        L1DispMuonEMTF: "all"