V32:
  DYLL_M50:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v32_reL1only/DYToLL_M-50_TuneCP5_14TeV-pythia8/DY_M50_131_200PU_v32_reL1only/240205_120621/0000/L1NtuplePhaseII_Step1_*.root
    trees_branches:
      genTree/L1GenTree:
        part_mu: [Id, Stat, Pt, Eta, Phi]
        part_e: [Id, Stat, Pt, Eta, Phi]
      l1PhaseIITree/L1PhaseIITree:
        tkElectron: [Pt, Et, Eta, Phi, Chg, Bx, TrkIso, PfIso, PuppiIso, zVtx, HwQual, HGC, PassesEleID, PassesPhoID]
        EG: [Pt, Et, Eta, Phi, Bx, Iso, HwQual, HGC, PassesEleID, PassesSaID]
        gmtMuon: [Pt, Eta, Phi, Z0, D0, IPt, IEta, IPhi, IZ0, ID0, Chg, Iso, Qual, Beta, Bx]
        gmtTkMuon: [Pt, Eta, Phi, Z0, D0, IPt, IEta, IPhi, IZ0, ID0, Chg, Iso, Qual, Beta, NStubs, Bx]
  TT:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v32_reL1only/TT_TuneCP5_14TeV-powheg-pythia8/TT_131_200PU_v32_reL1only/240206_115846/0000/L1NtuplePhaseII_Step1_*.root
    trees_branches:
      genTree/L1GenTree:
        # genMetTrue: "all"
        jet: [Pt, Eta, Phi]
      l1PhaseIITree/L1PhaseIITree:
        # puppiMET: "all"
        phase1PuppiJet: [Pt, Et, Eta, Phi]
        # phase1PuppiMHT: "all"
        # phase1PuppiHT: "all"
        seededConePuppiJet: [Pt, Et, Eta, Phi]
        seededConeExtendedPuppiJet: [Pt, Et, Eta, Phi, BJetNN]
        # seededConePuppiHT: "all"
        # seededConePuppiMHT: "all"
        trackerJet: [Pt, Eta, Phi]
        # trackerMET: "all"
        # trackerMHT: "all"
        # trackerHT: "all"
        # caloJet: "all"
        caloJet: [Et, Pt, Eta, Phi]
  #       ## DEBUG
  #       #tkElectron: [Pt, Et, Eta, Phi, Chg, Bx, TrkIso, PfIso, PuppiIso, zVtx, HwQual, HGC, PassesEleID, PassesPhoID]
  #       #tkPhoton: [Pt, Et, Eta, Phi, Bx, TrkIso, HwQual, HGC, PassesEleID, PassesPhoID]
  VBFHToTauTau:
    ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/14X/v32_reL1only/VBFHToTauTau_M-125_TuneCP5_14TeV-powheg-pythia8/VBFHToTauTau_131_200PU_v32_reL1only/240206_115854/0000/L1NtuplePhaseII_Step1_*.root
    trees_branches:
      genTree/L1GenTree:
        part_tau: [Id, Stat, Pt, Eta, Phi, Parent, E]
      l1PhaseIITree/L1PhaseIITree:
        nnTau: [Et, Eta, Pt, Phi, FullIso, Z0, PassTightNN, Chg, DXY, PassLooseNN]
        caloTau: [Et, Eta, Pt, Phi, Iso, HwQual, Bx]
  # HHToTauTau:
  #   ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/CMSSW_12_5_2p1/v29/HHToTauTau_1252_crab_v29_Snap3/230417_072539/0000/*.root
  #   trees_branches:
  #     genTree/L1GenTree:
  #       part_tau: [Id, Stat, Pt, Eta, Phi, Parent, E]
  #     l1PhaseIITree/L1PhaseIITree:
  #       nnTau: [Et, Eta, Pt, Phi, FullIso, Z0, PassTightNN, Chg, DXY, PassLooseNN]
  #       caloTau: [Et, Eta, Pt, Phi, Iso, HwQual]
  # Hgg:
  #   ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/CMSSW_12_5_2p1/v29/GluGluHToGG_1252_crab_v29_Snap3/230413_214505/0000/*.root
  #   trees_branches:
  #     genTree/L1GenTree:
  #       part_gamma: [Id, Stat, Pt, Eta, Phi]
  #     l1PhaseIITree/L1PhaseIITree:
  #       tkPhoton: [Pt, Et, Eta, Phi, Bx, TrkIso, HwQual, HGC, PassesEleID, PassesPhoID, TrkIsoPV]
  #       EG: [Pt, Et, Eta, Phi, Bx, Iso, HwQual, HGC, PassesEleID, PassesSaID]
  # MinBias:
  #   ntuple_path: /eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/alobanov/phase2/menu/ntuples/CMSSW_12_5_2p1/v29/MinBias_1252_crb_v29_Snap3/230413_214525/*/*.root
  #   trees_branches:
  #     l1PhaseIITree/L1PhaseIITree:
  #       puppiMET: "all"
  #       phase1PuppiJet: "all"
  #       phase1PuppiMHT: "all"
  #       phase1PuppiHT: "all"
  #       seededConePuppiJet: [Pt, Et, Eta, Phi]
  #       seededConeExtendedPuppiJet: [Pt, Et, Eta, Phi, BJetNN]
  #       seededConePuppiHT: "all"
  #       seededConePuppiMHT: "all"
  #       tkElectron: [Pt, Et, Eta, Phi, Chg, Bx, TrkIso, PfIso, PuppiIso, zVtx, HwQual, HGC, PassesEleID, PassesPhoID]
  #       EG: [Pt, Et, Eta, Phi, Bx, Iso, HwQual, HGC, PassesEleID, PassesSaID]
  #       gmtTkMuon: [Pt, Eta, Phi, Z0, D0, IPt, IEta, IPhi, IZ0, ID0, Chg, Iso, Qual, Beta, NStubs, Bx]
  #       nnTau: [Et, Eta, Pt, Phi, FullIso, Z0, PassTightNN, Chg, DXY, PassLooseNN]
  #       tkPhoton: [Pt, Et, Eta, Phi, Bx, TrkIso, HwQual, HGC, PassesEleID, PassesPhoID, TrkIsoPV]
  #       z0L1TkPV: "all"
  #       caloTau: [Et, Eta, Pt, Phi, Iso, HwQual, Bx]

