EGRates:
  sample: MinBias
  version: V38nano
  test_objects:
    - L1EG:default
    - L1tkElectron:NoIso
    - L1tkElectron:Iso
    - L1tkPhoton:Iso
    - L1tkElectron:NoIsoNoLowPtID
  binning:
    min: 10
    max: 97
    step: 3
