MHT_debug_METrefGenMHT:
  sample: TT
  version: V41nano
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen MHT"
    cuts:
      object:
        - "abs({eta}) < 2.4"
        - "{pt} > 30"
    trafo: "MHT"
  test_objects:
    L1puppiMET:default: "pt"
  #thresholds: [-1, 0, 70, 150, 500]
  thresholds: [150]
  # scalings:
  #   method: "naive"
  #   threshold: 0.50
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20

MHT_debug:
  sample: TT
  version: V41nano
  reference_object:
    object: "GenJet"
    x_arg: "pt"
    label: "Gen MHT"
    cuts:
      object:
        - "abs({eta}) < 2.4"
        - "{pt} > 30"
    trafo: "MHT"
  test_objects:
    L1puppiJetSC4sums:MHT: "pt"
  #thresholds: [-1, 0, 70, 150, 500]
  thresholds: [150]
  # scalings:
  #   method: "naive"
  #   threshold: 0.50
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20

MHT_debug_refL1MET:
  sample: TT
  version: V41nano
  reference_object:
    object: "L1puppiMET"
    x_arg: "pt"
    label: "Gen MHT"
  test_objects:
    L1puppiJetSC4sums:MHT: "pt"
  # thresholds: [-1, 0, 70, 150, 500]
  thresholds: [150]
  # scalings:
  #   method: "naive"
  #   threshold: 0.50
  xlabel: "Gen. MHT30 (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV)"
  binning:
    min: 0
    max: 500
    step: 20