ElectronsIsolation_Barrel:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  iso_vs_efficiency: True
  reference_object:
    GenPart:reference_electron:barrel: "pt"
  test_objects:
    L1tkElectron:NoIsoForIso: "relIso"
  xlabel: "Isolation"
  ylabel: "Efficiency (Barrel)"
  binning:
    min: 0
    max: 0.5
    step: 0.005

ElectronsIsolation_Endcap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  iso_vs_efficiency: True
  reference_object:
    GenPart:reference_electron_endcap: "pt"
  test_objects:
    L1tkElectron:NoIsoForIso: "relIso"
  xlabel: "Isolation"
  ylabel: "Efficiency (Endcap)"
  binning:
    min: 0
    max: 0.5
    step: 0.005

