ElectronsMatching_Eta_Pt10to25:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_electron_pt10to25: "eta"
  test_objects:
    L1EG:default: "eta"
    L1tkElectron:NoIso: "eta"
    # L1tkElectron:NoIsoNoLowPtID: "eta"
    L1tkElectron:Iso: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

ElectronsMatching_Eta_Pt25toInf:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_electron_pt25toInf: "eta"
  test_objects:
    L1EG:default: "eta"
    L1tkElectron:NoIso: "eta"
    # L1tkElectron:NoIsoNoLowPtID: "eta"
    L1tkElectron:Iso: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
