ElectronsMatchingBarrel:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_electron:barrel: "pt"
  test_objects:
    L1EG:default: "pt"
    L1tkElectron:NoIso: "pt"
    # L1tkElectron:NoIsoNoLowPtID: "pt"
    L1tkElectron:Iso: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 100
    step: 3

# ElectronsMatchingBarrel_wPrunedGenPart:
#   sample: DYLL_M50
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     GenPart:reference_electron:barrel: "pt"
#   test_objects:
#     L1EG:default: "pt"
#     L1tkElectron:NoIso: "pt"
#     L1tkElectron:Iso: "pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Barrel)"
#   binning:
#     min: 0
#     max: 100
#     step: 3

ElectronsMatchingEndcap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_electron_endcap: "pt"
  test_objects:
    L1EG:default: "pt"
    L1tkElectron:NoIso: "pt"
    # L1tkElectron:NoIsoNoLowPtID: "pt"
    L1tkElectron:Iso: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 100
    step: 3

# ElectronsMatchingEndcap_wPrunedGenPart:
#   sample: DYLL_M50
#   version: V44nano
#   match_test_to_ref: True
#   reference_object:
#     GenPart:reference_electron_endcap: "pt"
#   test_objects:
#     L1EG:default: "pt"
#     L1tkElectron:NoIso: "pt"
#     L1tkElectron:Iso: "pt"
#   xlabel: "Gen. $p_T$ (GeV)"
#   ylabel: "Matching Efficiency (Endcap)"
#   binning:
#     min: 0
#     max: 100
#     step: 3
