JetTurnonBarrelSC8:
  version: V44nano
  sample: TT
  match_test_to_ref: True
  reference_object:
    GenJetAK8:reference_barrel: "pt"
  test_objects:
    L1puppiJetSC8:default:barrel: "pt"
  thresholds: [150]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonEndcapSC8:
  version: V44nano
  sample: TT
  match_test_to_ref: True
  reference_object:
    GenJetAK8:reference_endcap: "pt"
  test_objects:
    L1puppiJetSC8:default:endcap: "pt"
  thresholds: [150]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonForwardSC8:
  version: V44nano
  sample: TT
  match_test_to_ref: True
  reference_object:
    GenJetAK8:reference_forward: "pt"
  test_objects:
    L1puppiJetSC8:default:forward: "pt"
  thresholds: [150]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 500
    step: 10
