MuonsMatchingBarrel:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_muon:barrel_muon: "pt"
  test_objects:
    L1gmtMuon:default:barrel: "pt"
    L1gmtTkMuon:default:barrel: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (barrel)"
  binning:
    min: 0
    max: 100
    step: 3

MuonsMatchingOverlap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_muon:overlap: "pt"
  test_objects:
    L1gmtMuon:default:overlap: "pt"
    L1gmtTkMuon:default:overlap: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (overlap)"
  binning:
    min: 0
    max: 100
    step: 3

MuonsMatchingEndcap:
  sample: DYLL_M50
  version: V44nano
  match_test_to_ref: True
  reference_object:
    GenPart:reference_muon:endcap_muon: "pt"
  test_objects:
    L1gmtMuon:default:endcap: "pt"
    L1gmtTkMuon:default:endcap: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (endcap)"
  binning:
    min: 0
    max: 100
    step: 3
