### General Values
# Jet: {50, 100, 150}
Jet: {25, 30, 35, 40, 45, 50, 55, 60, 70, 75, 80, 85, 90, 100, 120, 125, 130, 140, 150, 175}
#  Jet: {100, 120, 150, 175, 200, 250, 300} # Scalings for SC8, as min jet pt in nano is 100 GeV
Muon: {7, 9, 10, 12, 14, 15, 17, 20, 26, 25, 27, 30}
Tau: {27, 30, 40, 50, 60, 70}
EG: {7, 9, 12, 14, 15, 17, 20, 26, 25, 27, 30, 40, 50}
MET: {70, 80, 90, 100, 125, 150, 175, 200}
MHT: {70, 80, 90, 100, 125, 150, 175}
HT: {50, 100, 150, 200, 250, 300, 350, 400, 450, 500}

### Specific values:
L1TrackHT:HT:inclusive: {50, 100, 150, 200, 250}