JetMatching_Eta_Pt40To100:
  sample: TT
  version: V37nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetHisto:default: "eta"
    L1puppiJetSC4:default: "eta"
    L1caloJet:default: "eta"
    L1TrackJet:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf:
  sample: TT
  version: V37nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetHisto:default: "eta"
    L1puppiJetSC4:default: "eta"
    L1caloJet:default: "eta"
    L1TrackJet:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_Pt100ToInf_extEta:
  sample: TT
  version: V37nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 7"
  test_objects:
    L1caloJet:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5.5
    max: 5.5
    step: 0.25

JetMatching_Eta_SC8_Pt100ToInf:
  sample: TT
  version: V37nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJetAK8"
    x_arg: "eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetSC8:default: "eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25