JetSC8Rates_byRegion2:
  sample: MinBias
  version: V44nano
  test_objects:
    # - L1puppiJetSC4:default
    - L1puppiJetSC8:default
    - L1puppiJetSC8:default:inclusive
    - L1puppiJetSC8:default:barrel
    #- L1puppiJetSC8:default:endcap
  binning:
    min: 40
    max: 420
    step: 20
