BJetEff_pt:
  files:
    JetMatching_pt_pt30ToInf_genBJets_-999_V40nano:
      object: L1puppiExtJetSC4:bjetnn:inclusive
      dir: outputs/object_performance/V40nano/turnons/
      label: "Signal: Matched b-jets"
    JetMatching_pt_pt30ToInf_genNotBJets_-999_V40nano:
      object: L1puppiExtJetSC4:bjetnn:inclusive
      dir: outputs/object_performance/V40nano/turnons/
      label: "Background: Unmatched b-jets"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  watermark: "BJet_pt"
  save_dir: "outputs/object_performance/V40nano/turnons/"


BJetEff_Eta:
  files:
    JetMatching_Eta_pt30ToInf_genBJets_-999_V40nano:
      object: L1puppiExtJetSC4:bjetnn:inclusive
      dir: outputs/object_performance/V40nano/turnons/
      label: "Signal: Matched b-jets"
    JetMatching_Eta_pt30ToInf_genNotBJets_-999_V40nano:
      object: L1puppiExtJetSC4:bjetnn:inclusive
      dir: outputs/object_performance/V40nano/turnons/
      label: "Background: Unmatched b-jets"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency"
  watermark: "BJet_Eta"
  save_dir: "outputs/object_performance/V40nano/turnons/"
