JetMatching_Eta_pt40To100_ExtendedVsRegular:
  sample: TT
  version: V32nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 40"
        - "{pt} < 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetSC4:default: "Eta"
    L1puppiExtJetSC4:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (40-100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_pt100ToInf_ExtendedVsRegular:
  sample: TT
  version: V32nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 100"
      object:
        - "abs({eta}) < 5"
  test_objects:
    L1puppiJetSC4:default: "Eta"
    L1puppiExtJetSC4:default: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>100 GeV)"
  binning:
    min: -5
    max: 5
    step: 0.25

JetMatching_Eta_pt30ToInf_genBJets:
  sample: TT
  version: V32nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 30"
        - "abs({partonFlavour}) == 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_Eta_pt30ToInf_genNotBJets:
  sample: TT
  version: V32nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "Eta"
    label: "Gen Jets"
    cuts:
      event:
        - "{pt} > 30"
        - "abs({partonFlavour}) != 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "Eta"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency (>30 GeV)"
  binning:
    min: -2.4
    max: 2.4
    step: 0.25

JetMatching_pt_pt30ToInf_genBJets:
  sample: TT
  version: V32nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({partonFlavour}) == 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10

JetMatching_pt_pt30ToInf_genNotBJets:
  sample: TT
  version: V32nano
  match_test_to_ref: True
  reference_object: 
    object: "GenJet"
    x_arg: "pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({partonFlavour}) != 5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    L1puppiExtJetSC4:bjetnn: "pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency"
  binning:
    min: 30
    max: 200
    step: 10
